[package]
name = "hello-fluvio"
version = "0.1.0"
authors = ["Fábio Corrêa <feamcor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluvio = "0.3.4"
async-std = "1.0.0"
